name: Checkout

inputs:
  fetch-depth:
    default: 1
    required: false
  path:
    default: ''
    required: false
    description: ef
    type: string
  repository:
    default: ${{ github.repository }}
    required: false
    description: a repo
  ref:
    default: ''
    description: abc
    required: false
  token:
    default: ${{ github.token }}
    required: false
    description: def
    type: string
  default-branch:
    required: true
    type: string

runs:
  using: composite
  steps:
    - id: repo
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        if [[ "${{ inputs.repository }}" != "${{ github.repository }}" ]]
          then
            USING="default branch"
          else
            USING="$(gh api /repos/${{ inputs.repository }}/commits/${{ github.sha }}/branches-where-head --jq '.[0].name')"
        fi
        echo "::notice::Checkout: ${{ inputs.repository }} using ${USING}"
        echo "::set-output name=ref-exists::true"

    - if: steps.repo.outputs.ref-exists == 'true'
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - if: steps.repo.outputs.ref-exists == 'false'
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.default-branch }}
        token: ${{ inputs.token }}