name: Release

on:
  release:
    types: [published]

jobs:
  get_approval:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: cmflynn
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          exclude-workflow-initiator-as-approver: false
  deploy:
    needs: get_approval
    uses: ./.github/workflows/called.yml
    with:
      version: ${{ github.event.release.tag_name }}