name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  service:
    strategy:
      fail-fast: false
      matrix:
        target:
          - jimmy_api
          - jimmy_frontend
    uses: ./.github/workflows/called.yml
    with:
      version: ${{ github.event.release.tag_name }}