name: Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  is_changed:
    strategy:
      fail-fast: false
      matrix:
        target:
          - jimmy_api
          - jimmy_frontend
    uses: tj-actions/changed-files@v35
    with:
      files: |
        ${{ matrix.target }}/**
  deploy:
    needs: is_changed
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
     - run: echo ${{ is_changed.outputs.any_changed }}
