name: Release QA

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - jimmy_api
          - jimmy_frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get ${{ inputs.service_name }} changes
        id: get_changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            ${{ matrix.target }}/**
            .github/**

      - name: List changes
        run: |
          echo "${{ steps.get_changes.outputs.all_changed_files }}"
          echo "${{ steps.get_changes.outputs.any_changed }}"
      - name: Deploy
        if: steps.get_changes.outputs.any_changed == 'true'
        run: echo deploy ${{ matrix.target }}

    outputs:
      changed: ${{ steps.get_changes.outputs.any_changed }}
