name: jimmy Deploy

on:
  push:
    branches:
      - master
      - uat
      - prod
  release:
    types: [ published ]


jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
       

  deploy_main:
    if: github.ref_name == 'master'
    uses: ./.github/workflows/jimmy_cicd_deploy_stages.yml
    with:
      deploy_environment: 'main'
      version: 'latest'
    secrets: inherit

  get_approval:
    if: github.ref_name != 'master'
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: cmflynn,kapr1s

          # hacky... but alas https://github.com/actions/runner/issues/409
          minimum-approvals: ${{ github.event_name == 'release' && 2 || 1  }}

          issue-title: "promoting to ${{ github.ref_name }}"
          exclude-workflow-initiator-as-approver: false

  deploy_qa:
    if: github.event_name == 'release'
    uses: ./.github/workflows/jimmy_cicd_deploy_stages.yml
    with:
      deploy_environment: 'qa'
      version: ${{ github.event.release.tag_name }}
    secrets: inherit
  
  deploy_uat:
    if: github.ref_name == 'uat'
    uses: ./.github/workflows/jimmy_cicd_deploy_stages.yml
    with:
      deploy_environment: 'uat'
    secrets: inherit
  
  deploy_prod:
    if: github.ref_name == 'prod'
    uses: ./.github/workflows/jimmy_cicd_deploy_stages.yml
    with:
      deploy_environment: 'prod'
    secrets: inherit