name: Promote

on:
  push:
    branches:
      - uat

jobs:
  promote:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - jimmy_api
          - jimmy_frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - id: get_changes
        uses: tj-actions/changed-files@v35
        with:
          files: |
            ${{ matrix.target }}/**
            .github/**

      - name: List changes
        run: |
          echo "${{ steps.get_changes.outputs.all_changed_files }}"
          echo "${{ steps.get_changes.outputs.any_changed }}"
      - name: Deploy
        if: steps.get_changes.outputs.any_changed == 'true'
        run: |
          echo promote ${{ matrix.target }}
          echo ${{ github.ref_name }}

    outputs:
      changed: ${{ steps.get_changes.outputs.any_changed }}
