on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  checkout:
    name: ${{ inputs.repo }}_checkout
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
      - name: Checkout repository at branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Checkout repository at trunk
        if: failure() && steps.checkout.conclusion == 'failure'
        uses: actions/checkout@v3
        with:
          ref: feature/some-trunk
