on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  checkout:
    name: ${{ inputs.repo }}_checkout
    runs-on: ubuntu-latest # windows-latest | macos-latest
    steps:
      - name: Checkout repository at branch
        continue-on-error: true
        id: branch_checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          path: ${{ inputs.repo }}

      - name: Checkout repository at trunk
        if: steps.branch_checkout.outcome == 'failure'
        uses: actions/checkout@v3
        with:
          ref: feature/some-trunk
          path: ${{ inputs.repo }}

      - run: ls -al ${{ inputs.repo }}

      - uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.repo }}-${{ inputs.branch }}
          path: ./${{ inputs.repo }}