on:
  push:
    branches:
      - smoke

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/checkout
        with:
          repository: DriveWealth/mysolomeo_common
          ref: feature/fx
          path: mysolomeo_common
          token: ${{ secrets.DW_TOKEN }}
          default-branch: feature/fx

      - uses: ./.github/actions/checkout
        name: checkout unix-setup
        with:
          repository: cmflynn/unix-setup
          ref: ${{ github.ref_name }}
          path: unix-setup
          default-branch: feature/some-trunk

      - uses: ./.github/actions/checkout
        name: checkout markdown
        with:
          repository: cmflynn/markdown-cheatsheet
          ref: ${{ github.ref_name }}
          path: markdown-cheatsheet
          default-branch: feature/some-trunk

      - run: ls -al unix-setup
      - run: ls -al markdown-cheatsheet
